### ISSUE TITLE
esp32 not working with i2c wiring?

### ISSUE THREAD

**Issue by chcmq** [tueddy/CLRC663-Library#1]
![选区_054](https://user-images.githubusercontent.com/30547484/227949532-fde41fa4-dab2-4495-b8d7-8a08b67350bb.png)
I can make sure my wiring is fine

**Comment by tueddy** [comment]
Do you have modified the module as described?
You could use the [I2C scanner example ](https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire/examples/WireScan/WireScan.ino)to make sure wiring is OK & I2C address is 0x2A

**Comment by chcmq** [comment]
![image](https://user-images.githubusercontent.com/30547484/228419079-5ae4277a-319b-4f20-9751-f90940a82331.png)
Could you please provide the schematic diagram of this development board?

**Comment by tueddy** [comment]
Sorry, i have no schematic for this module. Just followed the instructions to switch to I2C here:
https://blog.edhayes.us/2022/02/23/clrc663-module-spi-i2c/
