### ISSUE TITLE
Please ask the card data how to encrypt verification

### ISSUE THREAD

**Issue by chcmq** [tueddy/CLRC663-Library#3]
Please ask the card data how to encrypt verification？Can you add related cases, thank you

**Comment by chcmq** [comment]
The current case seems to be just the data of the card reading. I need to verify the password of the card. How should I implement it?

**Comment by tueddy** [comment]
You mean the ICode-Slix2 password for privacy mode? 
In case of wrong password the tag is still not responding. [Here ](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L112)is an example

**Comment by chcmq** [comment]
> 你是说隐私模式的 ICode-Slix2 密码？ 如果密码错误，标签仍然没有响应。[这](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L112)是一个例子

I'm sorry I made a mistake, what I mean is how to update this password

**Comment by chcmq** [comment]
The tab has been unresponsive because I can't remember what its original password was, at which point I want to reset the password

**Comment by tueddy** [comment]
Documentation about the ICODE SLIX2 custom commands here:

9.5.3.2 SET PASSWORD / WRITE PASSWORD:
https://www.nxp.com/docs/en/data-sheet/SL2S2602.pdf

**Comment by chcmq** [comment]
> 有关 ICODE SLIX2 自定义命令的文档：
> 
> 9.5.3.2 设置密码/写入密码： https://www.nxp.com/docs/en/data-sheet/SL2S2602.pdf

Can you make a demo for this library?

**Comment by chcmq** [comment]
The random number returned after the 'ISO15693_getRandomNumber' method call is always negative. I don't know where the problem is.

**Comment by chcmq** [comment]
![image](https://user-images.githubusercontent.com/30547484/233977499-fe686b1a-8f82-4d2f-91d1-d2222baadd41.png)

**Comment by chcmq** [comment]
It seems that the random number can never be obtained, please help to find out what the problem is.
I can't currently set a new password because I can't get the correct random number, can you help me?

**Comment by tueddy** [comment]
Are you sure that your tag is a real ICode Slix tag? In your log  i can see a 14443 tag only, this is not ICode Slix!
You should see ISO-15693 in log. 14443  tags have no command GET RANDOM..

demo reads UID in two steps:
1. read ISO-14443 cards [here](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L96)
2. try to wake-up ISO-15693 cards from privacy mode and read the UID [here](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L112)

**Comment by chcmq** [comment]
I can't currently set a new password because I can't get the correct random number, can you help me?

> Are you sure that your tag is a real ICode Slix tag? In your log i can see a 14443 tag only, this is not ICode Slix! You should see ISO-15693 in log. 14443 tags have no command GET RANDOM..
> 
> demo reads UID in two steps:
> 
> 1. read ISO-14443 cards [here](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L96)
> 2. try to wake-up ISO-15693 cards from privacy mode and read the UID [here](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L112)

May I ask how to set it as an ICode Slix label? This is the first time I use this chip, so I don’t know much about it

**Comment by chcmq** [comment]
![image](https://user-images.githubusercontent.com/30547484/233983338-4e5a0d28-17ea-461f-8811-03c90f11fea1.png)

**Comment by tueddy** [comment]
There exists completely different type of tags: ISO14443 and ISO-15693 tags. ICode-Slix is an ISO-15693 substandard and have custom commands and an optional privacy mode. You should really check which kind of tags do you have.
In your log i see only an ISO-14443 tag..

**Comment by chcmq** [comment]
> 存在完全不同类型的标签：ISO14443 和 ISO-15693 标签。ICode-Slix 是 ISO-15693 子标准，具有自定义命令和可选的隐私模式。你真的应该检查你有哪种标签。 在你的日志中我只看到一个 ISO-14443 标签..

My log is just to test the Demo of this library. I didn’t find how to set ISO-15693 tags in this library.
