### ISSUE TITLE
How to set the card reading method to ISO-15693 tags

### ISSUE THREAD

**Issue by chcmq** [tueddy/CLRC663-Library#4]
How to set the card reading method to ISO-15693 tags

**Comment by tueddy** [comment]
The demo shows reading an ISO-15693 tag [here](https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L112)
