### ISSUE TITLE
I²C

### ISSUE THREAD

**Issue by catalinalb** [tueddy/CLRC663-Library#8]
Hello,

Is there example for the I²C bus for this IC?

Thank you

**Comment by tueddy** [comment]
Hi, you can use the standard demo and change between SPI and I2C here:

https://github.com/tueddy/CLRC663-Library/blob/415b58310778fc40a6500787fe8b59134b85ea18/examples/CLRC663-Demo/CLRC663-Demo.ino.cpp#L56

**Comment by catalinalb** [comment]
Thanks, I will try this!
I am currently connected on a raspberry pi and the address of the clrc663 is 2b.
Do you know if I can find a similar example code in C or python that I, could just run from the command line?

Thank you!

**Comment by tueddy** [comment]
You can change I2C address in constructor (0x2A -> 0x2b).
I don't know if any other code exists for this reader..

**Comment by catalinalb** [comment]
Hello again,

I am running the sketch on ESP32-Wroom-32.
I did enable the I²C and added the right address. 
I also connected the IRQ wire but what about CS wire number 5 CHIP Select
Is that still needed if I run it over i²c ? or is just for SPI ?

Thank you,
Catalin

**Comment by tueddy** [comment]
For I2C you just need SCL and SDA (serial clock & serial data).
CS is for SPI only.
